travis:
  secure:
    BINSTAR_TOKEN: Thq5oOsCUKFV1X+USKG5MYy9OEchA6QZ85NalraB1lU6GvG9QDppYuKlVWSwynlTCE9dNBFVScPnF6ylOqVNavs6FOsMp7gu9bc1HXecf3elrcnyZDQwBhYwwfdl/XUEJD6jpFoetRIS2XcyxfHuKDOk1UZyDaJoF8iBdtXw8Ovg5JGGBL9/eiv5QPsabjy742ujC/Tga7CkGiiab2dYfsxlmpQRt+CaYFI80+Ng3iXqRxCPK5NvPedQ691foau5f7rAhKuOAQQSBdk6uKWuNeU6Gmy2t4uv3Wgbqdj9zD88G8LQJtXkgdl5cd/mLV5aPhnK5IN/Hua5D7/mouyqRTXkIM52t6kqAtdvWnxlauy18ODsGOcr3RaZCb4AgLY69s0DsOvw7lbNy1nwFYaG2FuW6s5K1xF5VZpzqQJVbvgmzDmLGnDkLPxnQMoB62gf5tAMGFLPRvkSTrvxlIita3jhmuAny8HNTWLFM4xnKloqHQLIAedyS0ba7CucmXl2+FJ23UJ2sV34hgf1PAYoKj0EV5CoAOwViQT0pZRPWr3GJLyt06P4xwIHZJqY8lRUikBzMMVn3cVqiu90+v6bj2Gck+62830EM0Fy0UE8nzQj3DFhOktTJS/enxQRvm1bDfvEN6IFKa6UUupjxVOamzO6HIXmdRZv76z0YFOIxzs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
